<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Admin\CancellationReason;

class CancellationReasonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    protected $cancelation_reason = [
       [ 'user_type' => 'user',
          'transport_type' => 'taxi',
         'payment_type' => 'free',
         'arrival_status' => 'before',
         'reason' => 'Esperando motorista por muito tempo',
         'active' => 1,
         'company_key' => null,],
       [ 'user_type' => 'user',
          'transport_type' => 'taxi',
         'payment_type' => 'free',
         'arrival_status' => 'after',
         'reason' => 'Motorista Bebeu',
         'active' => 1,
         'company_key' => null,],
       [ 'user_type' => 'user',
          'transport_type' => 'taxi',
         'payment_type' => 'compensate',
         'arrival_status' => 'after',
         'reason' => 'Motorista Muito Atrasado',
         'active' => 1,
         'company_key' => null,],
       [ 'user_type' => 'user',
          'transport_type' => 'taxi',
         'payment_type' => 'compensate',
         'arrival_status' => 'before',
         'reason' => 'Auto Cancelamento',
         'active' => 1,
         'company_key' => null,],

         [ 'user_type' => 'driver',
          'transport_type' => 'taxi',
         'payment_type' => 'free',
         'arrival_status' => 'before',
         'reason' => 'Usuário Cancelou',
         'active' => 1,
         'company_key' => null,],
         [ 'user_type' => 'driver',
          'transport_type' => 'taxi',
         'payment_type' => 'free',
         'arrival_status' => 'after',
         'reason' => 'Usuário Não Atende Chamadas',
         'active' => 1,
         'company_key' => null,],
         [ 'user_type' => 'driver',
          'transport_type' => 'taxi',
         'payment_type' => 'compensate',
         'arrival_status' => 'before',
         'reason' => 'Auto Cancelamento',
         'active' => 1,
         'company_key' => null,],
         [ 'user_type' => 'driver',
          'transport_type' => 'taxi',
         'payment_type' => 'compensate',
         'arrival_status' => 'after',
         'reason' => 'Usuário Muito Atrasado',
         'active' => 1,
         'company_key' => null,],
       [ 'user_type' => 'user',
          'transport_type' => 'delivery',
         'payment_type' => 'free',
         'arrival_status' => 'before',
         'reason' => 'Esperando motorista por muito tempo',
         'active' => 1,
         'company_key' => null,],
       [ 'user_type' => 'user',
          'transport_type' => 'delivery',
         'payment_type' => 'free',
         'arrival_status' => 'after',
         'reason' => 'Motorista Bebeu',
         'active' => 1,
         'company_key' => null,],
       [ 'user_type' => 'user',
          'transport_type' => 'delivery',
         'payment_type' => 'compensate',
         'arrival_status' => 'after',
         'reason' => 'Motorista Muito Atrasado',
         'active' => 1,
         'company_key' => null,],
       [ 'user_type' => 'user',
          'transport_type' => 'delivery',
         'payment_type' => 'compensate',
         'arrival_status' => 'before',
         'reason' => 'Auto Cancelamento',
         'active' => 1,
         'company_key' => null,],
        ['user_type' => 'driver',
          'transport_type' => 'delivery',
         'payment_type' => 'free',
         'arrival_status' => 'before',
         'reason' => 'Usuário Cancelou',
         'active' => 1,
         'company_key' => null,],
        [ 'user_type' => 'driver',
          'transport_type' => 'delivery',
         'payment_type' => 'free',
         'arrival_status' => 'after',
         'reason' => 'Usuário Não Atende Chamadas',
         'active' => 1,
         'company_key' => null,],
        [ 'user_type' => 'driver',
          'transport_type' => 'delivery',
         'payment_type' => 'compensate',
         'arrival_status' => 'before',
         'reason' => 'Auto Cancelamento',
         'active' => 1,
         'company_key' => null,],
        [ 'user_type' => 'driver',
          'transport_type' => 'delivery',
         'payment_type' => 'compensate',
         'arrival_status' => 'after',
         'reason' => 'Usuário Muito Atrasado',
         'active' => 1,
         'company_key' => null,],

        //
        [ 'user_type' => 'user',
          'transport_type' => 'taxi',
         'payment_type' => 'free',
         'arrival_status' => 'before',
         'reason' => 'Transporte Alternativo',
         'active' => 1,
         'company_key' => null,],
        [ 'user_type' => 'user',
          'transport_type' => 'delivery',
         'payment_type' => 'free',
         'arrival_status' => 'before',
         'reason' => 'Motivos Financeiros',
         'active' => 1,
         'company_key' => null,],
        [ 'user_type' => 'user',
          'transport_type' => 'taxi',
         'payment_type' => 'free',
         'arrival_status' => 'after',
         'reason' => 'Problemas com o Veículo',
         'active' => 1,
         'company_key' => null,],
        [ 'user_type' => 'user',
          'transport_type' => 'taxi',
         'payment_type' => 'free',
         'arrival_status' => 'before',
         'reason' => 'Motivos Pessoais',
         'active' => 1,
         'company_key' => null,],
        [ 'user_type' => 'user',
          'transport_type' => 'delivery',
         'payment_type' => 'free',
         'arrival_status' => 'after',
         'reason' => 'Motivos Pessoais',
         'active' => 1,
         'company_key' => null,],

        [ 'user_type' => 'user',
          'transport_type' => 'taxi',
         'payment_type' => 'free',
         'arrival_status' => 'after',
         'reason' => 'Preocupações com Segurança',
         'active' => 1,
         'company_key' => null,],

        [ 'user_type' => 'user',
          'transport_type' => 'taxi',
         'payment_type' => 'free',
         'arrival_status' => 'before',
         'reason' => 'Condições Climáticas',
         'active' => 1,
         'company_key' => null,],

        //
        [ 'user_type' => 'driver',
          'transport_type' => 'taxi',
         'payment_type' => 'free',
         'arrival_status' => 'before',
         'reason' => 'Problemas com o Veículo',
         'active' => 1,
         'company_key' => null,],
        [ 'user_type' => 'driver',
          'transport_type' => 'taxi',
         'payment_type' => 'free',
         'arrival_status' => 'before',
         'reason' => 'Trânsito ou Condições da Estrada',
         'active' => 1,
         'company_key' => null,],
        [ 'user_type' => 'driver',
          'transport_type' => 'taxi',
         'payment_type' => 'free',
         'arrival_status' => 'after',
         'reason' => 'Passageiro Não Compareceu',
         'active' => 1,
         'company_key' => null,],
        [ 'user_type' => 'driver',
          'transport_type' => 'taxi',
         'payment_type' => 'free',
         'arrival_status' => 'after',
         'reason' => 'Comportamento Inadequado do Passageiro',
         'active' => 1,
         'company_key' => null,],
        [ 'user_type' => 'driver',
          'transport_type' => 'taxi',
         'payment_type' => 'free',
         'arrival_status' => 'before',
         'reason' => 'Conflitos de Agenda',
         'active' => 1,
         'company_key' => null,],
        [ 'user_type' => 'driver',
         'transport_type' => 'taxi',
        'payment_type' => 'free',
        'arrival_status' => 'before',
        'reason' => 'Condições Climáticas',
        'active' => 1,
        'company_key' => null,],
        [ 'user_type' => 'driver',
         'transport_type' => 'taxi',
        'payment_type' => 'free',
        'arrival_status' => 'after',
        'reason' => 'Má Comunicação ',
        'active' => 1,
        'company_key' => null,],

    ];

    public function run()
    {
      $created_params = $this->cancelation_reason;

      $value = CancellationReason::first();

      if(is_null($value))
      {
        foreach ($created_params as $reason)
        {
          CancellationReason::create($reason);
        }
      }
      // else {
      //   foreach ($created_params as $reason)
      //   {
      //     $value->update($reason);
      //   }

      // }

    }
}
